"""init

Revision ID: 3d626330e60d
Revises: 71771b94ce6b
Create Date: 2023-10-06 15:15:08.704604+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d626330e60d'
down_revision: Union[str, None] = '71771b94ce6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('terms',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_table('module_grade_structure',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('structure_type', sa.Text(), nullable=False),
    sa.Column('weightage', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('modules_coordinators',
    sa.Column('coordinator_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('coordinator_id', 'module_id')
    )
    op.create_table('modules_lecturers',
    sa.Column('coordinator_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('coordinator_id', 'module_id')
    )
    op.create_table('modules_students',
    sa.Column('coordinator_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Numeric(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('coordinator_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules_students')
    op.drop_table('modules_lecturers')
    op.drop_table('modules_coordinators')
    op.drop_table('module_grade_structure')
    op.drop_table('terms')
    op.drop_table('modules')
    # ### end Alembic commands ###
