"""init

Revision ID: e8792a751402
Revises: 25e856c776a2
Create Date: 2023-10-09 08:43:05.942432+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8792a751402'
down_revision: Union[str, None] = '25e856c776a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_grade_structure', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_grade_structure', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
