"""init

Revision ID: f4d341961a30
Revises: 6633d2827a33
Create Date: 2023-10-07 13:15:40.403440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d341961a30'
down_revision: Union[str, None] = '6633d2827a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules_lecturers', sa.Column('term_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules_lecturers', 'terms', ['term_id'], ['term_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules_lecturers', type_='foreignkey')
    op.drop_column('modules_lecturers', 'term_id')
    # ### end Alembic commands ###
