"""init

Revision ID: 927e1343fd19
Revises: 3d626330e60d
Create Date: 2023-10-06 20:16:19.907444+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927e1343fd19'
down_revision: Union[str, None] = '3d626330e60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('module_code', sa.Text(), nullable=False))
    op.add_column('modules', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'credits')
    op.drop_column('modules', 'module_code')
    # ### end Alembic commands ###
